### ISSUE TITLE
Downloading varnisls is not working - 404 for varnishls-x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by mateusz-kolecki** [auduny/vscode-vcl#3]
After installing the extension the output shows only one line:

```
INFO [4.03.2024, 11:49:29]: Server URL: https://github.com/M4R7iNP/varnishls/releases/download/v0.0.9.1/varnishls-x86_64-unknown-linux-musl
```

And the link gives 404.

Result: the extension is not giving any autocompletion. 

Looks like starting from `v0.0.9.1` the file `varnishls-x86_64-unknown-linux-musl` is no longer build and instead `varnishls-x86_64-unknown-linux-gnu` is available for Linux platform.

Link to the varnishls releases: https://github.com/M4R7iNP/varnishls/releases/

Installed extension version: 0.6.1

**Comment by auduny** [comment]
Ouch, I'll look into it as soon as possible
